### ISSUE TITLE
How to reset the filter full

### ISSUE THREAD

**Issue by deam0n** [wichers/esphome-comfoair#18]
Hi wichers,

how to reset the filter full status?

**Comment by deam0n** [comment]
After a closer look, I've added the reset_filter() to the FOCUS FAN MODE:
```
 this->fan_mode = *call.get_fan_mode();
      switch (this->fan_mode.value()) {
        case climate::CLIMATE_FAN_FOCUS:
	  reset_filter();
          break;

        case climate::CLIMATE_FAN_HIGH:
          level = 0x04;
          break;
```

and added the button on the dashboard as follows:
![image](https://user-images.githubusercontent.com/1869650/171064448-2a6c5dd2-c73f-4958-aa97-f73ab36e8906.png)

```
type: vertical-stack
cards:
  - type: custom:simple-thermostat
    entity: climate.comfoair
    hide:
      state: true
      temperature: true
    header:
      name: Ventilation
    control:
      fan:
        'off':
          name: 'Off'
          icon: mdi:fan-minus
        auto:
          name: Auto
          icon: mdi:fan-auto
        low:
          name: Low
          icon: mdi:fan-speed-1
        medium:
          name: Medium
          icon: mdi:fan-speed-2
        high:
          name: High
          icon: mdi:fan-speed-3
        focus:
          name: Reset Filter
          icon: mdi:air-filter
    layout:
      mode:
        headings: false
        names: true
        icons: true
    sensors:
      - entity: sensor.bedroom_sensor_temperature
        name: Bedroom
      - entity: sensor.small_bedroom_motion_temperature
        name: Small Bedroom
      - entity: sensor.bathroom_motion_temperature
        name: Bathroom
      - entity: sensor.bathroom_humidity_sensor_humidity
        name: Bathroom humidity
      - entity: sensor.living_room_sensor_temperature
        name: Living Room
  - type: custom:comfoair-card
    entity: climate.comfoair
```

I got the successfull clear log message! After the first reset filter I was no longer able to reset again (but probably because the filter is now not reporting as full...)

It would be great to have a UI button for this..  Maybe on comfoair.yaml something alike:
```
button:
  - platform: restart
    name: "Comfoair ESP Restart"
```
but for the reset_filter().
